**Task 1**


*   What kind of data set is this? Provide some context by saying a little about what kind of
objects we are talking about, and what kind of attributes they have.


**This datasets contains information about COVID-19 in 8 tables.**

In [11]:
import pandas as pd

covid_19_data = pd.read_csv('covid_19_data.csv')
COVID19_line_list_data = pd.read_csv('COVID19_line_list_data.csv')
COVID19_open_line_list = pd.read_csv('COVID19_open_line_list.csv')
time_series_covid_19_confirmed = pd.read_csv('time_series_covid_19_confirmed.csv')
time_series_covid_19_confirmed_US = pd.read_csv('time_series_covid_19_confirmed_US.csv')
time_series_covid_19_deaths = pd.read_csv('time_series_covid_19_deaths.csv')
time_series_covid_19_deaths_US = pd.read_csv('time_series_covid_19_deaths_US.csv')
time_series_covid_19_recovered = pd.read_csv('time_series_covid_19_recovered.csv')

 <h4>covid_19_data.csv contains daily updates for covid-19 updates in different locations.</h4>
 <table style="width:100%">
  <tr>
    <th>Column</th>
    <th>Content</th>
    <th>Type</th>
  </tr>
  <tr>
    <td>SNo</td>
    <td>Unique ID</td>
    <td>int64</td>
  </tr>
  <tr>
    <td>ObservationDate</td>
    <td>Date of recording</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Province/State</td>
    <td>Province or state of the observation</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Country/Region</td>
    <td>Country or region of the observation</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Last Update</td>
    <td>Last update for the location</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Confirmed</td>
    <td>Confirmed covid-19 cases</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>Deaths</td>
    <td>Confirmed covid-19 deaths</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>Recovered</td>
    <td>Confirmed covid-19 recovered patients</td>
    <td>float64</td>
  </tr>
</table>

 <h4>COVID19_line_list_data.csv contains information about the first covid-19 patients</h4>
 <table style="width:100%">
  <tr>
    <th>Column</th>
    <th>Content</th>
    <th>Type</th>
  </tr>
  <tr>
    <td>id</td>
    <td>Unique ID</td>
    <td>int64</td>
  </tr>
  <tr>
    <td>case_in_country</td>
    <td>Aggregated total cases in location</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>reporting date</td>
    <td>Date of report</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Unnamed: 3 </td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>summary</td>
    <td>Text summarizing the row</td>
    <td>str</td>
  </tr>
  <tr>
    <td>location</td>
    <td>Location of the instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>country</td>
    <td>Country of the instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>gender</td>
    <td>Gender of the patient</td>
    <td>str</td>
  </tr>
  <tr>
    <td>age</td>
    <td>Age of the patient</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>symptom_onset</td>
    <td>Date of first experienced symptoms</td>
    <td>str</td>
  </tr>
  <tr>
    <td>If_onset_approximated</td>
    <td>if symptom_onset was approximated</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>hosp_visit_date</td>
    <td>Date visiting the hospital</td>
    <td>str</td>
  </tr>
  <tr>
    <td>exposure_start</td>
    <td>Date of exposure start</td>
    <td>str</td>
  </tr>
  <tr>
    <td>exposure_end</td>
    <td>Date of exposure end</td>
    <td>str</td>
  </tr>
  <tr>
    <td>visiting Wuhan</td>
    <td>If the patient is visiting wuhan</td>
    <td>int64</td>
  </tr>
  <tr>
    <td>from Wuhan</td>
    <td>If the patient is from wuhan</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>death</td>
    <td>if the patient died</td>
    <td>str</td>
  </tr>
  <tr>
    <td>recovered</td>
    <td>if the patient recovered or date of recovery</td>
    <td>str</td>
  </tr>
  <tr>
    <td>symptom</td>
    <td>List of symptoms</td>
    <td>str</td>
  </tr>
  <tr>
    <td>source</td>
    <td>Source that confirms the case</td>
    <td>str</td>
  </tr>
  <tr>
    <td>link</td>
    <td>Link that confirms the case</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Unnamed: 21</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>Unnamed: 22</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>Unnamed: 23</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>Unnamed: 24</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Unnamed: 25</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>Unnamed: 26</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>
</table>

<h4>COVID19_open_line_list.csv contains information about the first covid-19 patients</h4>
<table style="width:100%">
   <tr>
    <th>Column</th>
    <th>Content</th>
    <th>Type</th>
  </tr>
  <tr>
    <td>ID</td>
    <td>Unique ID for the patient</td>
    <td>int</td>
  </tr>
  <tr>
    <td>age</td>
    <td>Age of the patient</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>sex</td>
    <td>Sex of the patient</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>city</td>
    <td>City of instance, sometimes contains district</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>province</td>
    <td>Province of instance</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>country</td>
    <td>Country of instance</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>wuhan(0)_not_wuhan(1)</td>
    <td>Wether the patient has some relation to Wuhan</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>latitude</td>
    <td>Latitude of instance, with noise to prevent link to person</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>longitude</td>
    <td>Longitude of instance, with noise to prevent link to person</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>geo_resolution</td>
    <td>Has something to do with coordinates and location</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>date_onset_symptoms</td>
    <td>Date of first symptoms</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>date_admission_hospital</td>
    <td>Date admittet at the hospital</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>date_confirmation</td>
    <td>Date of patient confirmed covid-19 infection</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>symptoms</td>
    <td>Covid-19 symptoms experienced by the patient</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>lives_in_Wuhan</td>
    <td>Weather the patient lives in Wuhan</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>travel_history_dates</td>
    <td>Last date of travel</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>travel_history_location</td>
    <td>Places patient has recently visited</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>reported_market_exposure</td>
    <td>Reletionship of patient and market of covid-19 origin</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>additional_information</td>
    <td>Additional information about recent travels</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>chronic_disease_binary</td>
    <td>If the patient has chronic disease</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>chronic_disease</td>
    <td>Chronic disease of patient</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>source</td>
    <td>Link to a source</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>sequence_available</td>
    <td>Contains null values and one 'yes'</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>outcome</td>
    <td>Patient state after measurement</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>date_death_or_discharge</td>
    <td>Date of death or discharge</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>notes_for_discussion</td>
    <td>Notes, links and map locations relating to the instance</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>location</td>
    <td>Area of instance inside of district</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>admin3</td>
    <td>District of instance</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>admin2</td>
    <td>City of instance, reduntant with 'city'</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>admin1</td>
    <td>Province of instance, redunctant with 'province'</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>country_new</td>
    <td>Country of instance, redundant with 'country'</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>admin_id</td>
    <td>Unique id for admin</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>data_moderator_initials</td>
    <td>Initials of what I think is one admin, rest is null values</td>
    <td>str</td>
  </tr>  
  <tr>
    <td>Unnamed: 33</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Unnamed: 34</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Unnamed: 35</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Unnamed: 36</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Unnamed: 37</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Unnamed: 37</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Unnamed: 38</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Unnamed: 39</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Unnamed: 40</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Unnamed: 41</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Unnamed: 42</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Unnamed: 43</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Unnamed: 44</td>
    <td>Contains null values</td>
    <td>float64</td>
  </tr>
</table>

<h4>time_series_covid_19_confirmed.csv contains daily updates for confirmed covid-19 cases per location</h4>
<table style="width:100%">
   <tr>
    <th>Column</th>
    <th>Content</th>
    <th>Type</th>
  </tr>
  <tr>
    <td>Province/State</td>
    <td>Province or state of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Country/Region</td>
    <td>Country or region of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Lat</td>
    <td>Latitude of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Long</td>
    <td>Longitude of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>1/22/20 - 9/23/20</td>
    <td>Aggregated sum of cases at spesified date for each location</td>
    <td>str</td>
  </tr>
</table>

 <h4>time_series_covid_19_deaths.csv contains daily updates for covid-19 deaths per location</h4>
<table style="width:100%">
   <tr>
    <th>Column</th>
    <th>Content</th>
    <th>Type</th>
  </tr>
  <tr>
    <td>Province/State</td>
    <td>Province or state of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Country/Region</td>
    <td>Country or region of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Lat</td>
    <td>Latitude of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Long</td>
    <td>Longitude of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>1/22/20 - 9/23/20</td>
    <td>Aggregated sum of deaths at spesified date for each location</td>
    <td>str</td>
  </tr>
</table>

 <h4>time_series_covid_19_recovered.csv contains daily updates for recovered covid-19 patients per lecation</h4>
<table style="width:100%">
   <tr>
    <th>Column</th>
    <th>Content</th>
    <th>Type</th>
  </tr>
  <tr>
    <td>Province/State</td>
    <td>Province or state of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Country/Region</td>
    <td>Country or region of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Lat</td>
    <td>Latitude of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Long</td>
    <td>Longitude of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>1/22/20 - 9/23/20</td>
    <td>Aggregated sum of deaths at spesified date for each location</td>
    <td>str</td>
  </tr>
</table>

 <h4>time_series_covid_19_confirmed_US.csv contains daily updates for confimed covid-19 cases in the US per location</h4>
<table style="width:100%">
   <tr>
    <th>Column</th>
    <th>Content</th>
    <th>Type</th>
  </tr>
  <tr>
    <td>UID</td>
    <td>Unique identifier for each instance</td>
    <td>int64</td>
  </tr>
  <tr>
    <td>iso2</td>
    <td>two letter representation for country name (US only)</td>
    <td>str</td>
  </tr>
  <tr>
    <td>iso3</td>
    <td>three letter representation for country name (USA only)</td>
    <td>str</td>
  </tr>
  <tr>
    <td>code3</td>
    <td>An unknown number</td>
    <td>int64</td>
  </tr>
  <tr>
    <td>FIPS</td>
    <td>A unique number for each instance</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>Admin2</td>
    <td>County of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Province_State</td>
    <td>State of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Country_Region</td>
    <td>Country of instance (US only)</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Lat</td>
    <td>Latitude of county</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>Long_</td>
    <td>Longitude of county</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Combined_Key</td>
    <td>Combined string of county, state and country</td>
    <td>str</td>
  </tr>   
  <tr>
    <td>1/22/20 - 9/23/20</td>
    <td>Aggregated sum of deaths at spesified date for each location</td>
    <td>str</td>
  </tr>
</table>

 <h4>time_series_covid_19_deaths_US.csv contains daily updates for covid-19 deaths in the US per location</h4>
<table style="width:100%">
   <tr>
    <th>Column</th>
    <th>Content</th>
    <th>Type</th>
  </tr>
  <tr>
    <td>UID</td>
    <td>Unique identifier for each instance</td>
    <td>int64</td>
  </tr>
  <tr>
    <td>iso2</td>
    <td>two letter representation for country name (US only)</td>
    <td>str</td>
  </tr>
  <tr>
    <td>iso3</td>
    <td>three letter representation for country name (USA only)</td>
    <td>str</td>
  </tr>
  <tr>
    <td>code3</td>
    <td>An unknown number</td>
    <td>int64</td>
  </tr>
  <tr>
    <td>FIPS</td>
    <td>A unique number for each instance</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>Admin2</td>
    <td>County of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Province_State</td>
    <td>State of instance</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Country_Region</td>
    <td>Country of instance (US only)</td>
    <td>str</td>
  </tr>
  <tr>
    <td>Lat</td>
    <td>Latitude of county</td>
    <td>float64</td>
  </tr>
  <tr>
    <td>Long_</td>
    <td>Longitude of county</td>
    <td>float64</td>
  </tr>  
  <tr>
    <td>Combined_Key</td>
    <td>Combined string of county, state and country</td>
    <td>str</td>
  </tr>   
  <tr>
    <td>1/22/20 - 9/23/20</td>
    <td>Aggregated sum of deaths at spesified date for each location</td>
    <td>str</td>
  </tr>
</table>

In [79]:
df = time_series_covid_19_recovered
df.columns

Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '9/14/20', '9/15/20', '9/16/20', '9/17/20', '9/18/20', '9/19/20',
       '9/20/20', '9/21/20', '9/22/20', '9/23/20'],
      dtype='object', length=250)

In [78]:
df = time_series_covid_19_deaths
df.columns

Index(['Province/State', 'Country/Region', 'Lat', 'Long', '1/22/20', '1/23/20',
       '1/24/20', '1/25/20', '1/26/20', '1/27/20',
       ...
       '9/14/20', '9/15/20', '9/16/20', '9/17/20', '9/18/20', '9/19/20',
       '9/20/20', '9/21/20', '9/22/20', '9/23/20'],
      dtype='object', length=250)

In [74]:
df = time_series_covid_19_confirmed
df.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,9/14/20,9/15/20,9/16/20,9/17/20,9/18/20,9/19/20,9/20/20,9/21/20,9/22/20,9/23/20
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,38772,38815,38855,38872,38883,38919,39044,39074,39096,39145
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,11520,11672,11816,11948,12073,12226,12385,12535,12666,12787
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,48496,48734,48966,49194,49413,49623,49826,50023,50214,50400
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,1438,1438,1483,1483,1564,1564,1564,1681,1681,1753
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,3439,3569,3675,3789,3848,3901,3991,4117,4236,4363

In [72]:
df = COVID19_open_line_list

In [3]:
df = covid_19_data
df.rename(columns = {'ObservationDate':'observation_date', 
                              'Country/Region':'location',
                              'Last Update':'last_update',
                              'Confirmed':'confirmed',
                              'Deaths':'deaths',
                              'Recovered':'recovered'}, 
                   inplace = True)

In [6]:
df = COVID19_line_list_data
df.rename(columns = {'If_onset_approximated':'if_onset_approximated'}, 
                   inplace = True)